spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:6033/money-mind
    username: root
    password: sft6033
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      cache:
        period: 0
  config:
    import:
      optional:configserver:
